create table person (
    id int primary key generated by default as identity ,
    username varchar(20) not null,
    password varchar not null,
    role varchar not null default 'ROLE_USER'
);

create table refresh_token (
    id int primary key generated by default as identity ,
    person_id int references person(id) not null,
    refresh_token varchar not null,
    unique (person_id, refresh_token)
);

create table zone (
    id int primary key generated by default as identity,
    title varchar(30) unique not null,
    type_name varchar(30) not null,
    speed int not null check (speed <= 20),
    area polygon not null
);

create table firebase_token (
    id int primary key generated by default as identity,
    person_id int references person(id) not null,
    token varchar not null
);